name: Bug Report
description: Report an error or problem with the repository
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to report an issue!"
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      options:
        - Website display issue
        - Incorrect tool information
        - Broken link
        - Other
    validations:
      required: true
  - type: input
    id: affected-tool
    attributes:
      label: Affected Tool
      description: Which tool is affected (if applicable)
      placeholder: "e.g. VirSorter2"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the issue? Please be specific.
      placeholder: "Describe the issue in detail..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Paste or drag screenshots here"
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be relevant to the issue