blank_issues_enabled: true
contact_links:
  - name: Awesome Virome Documentation
    url: https://github.com/shandley/awesome-virome#readme
    about: Check our documentation first to see if your question is already answered
  - name: Repository Contributors
    url: https://github.com/shandley/awesome-virome/graphs/contributors
    about: See the team behind this project