name: Citation Source Visualization

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 2 * * 1'  # Run every Monday at 2 AM UTC
  push:
    paths:
      - 'impact_data.json'
      - 'scripts/citation_source_heatmap.py'

jobs:
  generate-visualizations:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Add source attribution if missing
        run: |
          echo "Checking for citation source attribution in impact_data.json..."
          if ! grep -q "citation_source" impact_data.json; then
            echo "Citation source attribution missing - adding it..."
            
            # Create a simple script to add attribution
            cat > add_attribution.py << 'EOF'
#!/usr/bin/env python3
import json
import os

# Load impact data
with open('impact_data.json', 'r') as f:
    impact_data = json.load(f)

# Check if we need to add attribution
citation_sources = {}
yearly_citation_sources = {}
tools_changed = 0

# Process each tool
for tool in impact_data.get('tools', []):
    # Only process tools with citations
    if tool.get('total_citations', 0) > 0:
        # Add citation source if missing
        if 'citation_source' not in tool:
            source = tool.get('primary_source', 'unknown')
            tool['citation_source'] = source
            citation_sources[source] = citation_sources.get(source, 0) + 1
            tools_changed += 1
            
        # Add yearly citation source if missing
        if 'yearly_citation_source' not in tool and tool.get('citations_by_year'):
            source = tool.get('yearly_data_source', tool.get('citation_source', 'unknown'))
            tool['yearly_citation_source'] = source
            yearly_citation_sources[source] = yearly_citation_sources.get(source, 0) + 1
            tools_changed += 1

# Add summary section if changed
if tools_changed > 0:
    impact_data['citation_sources'] = {
        'total_citations': citation_sources,
        'yearly_citations': yearly_citation_sources
    }
    
    # Save updated impact data
    with open('impact_data.json', 'w') as f:
        json.dump(impact_data, f, indent=2)
    
    print(f"Added attribution to {tools_changed} tools")
else:
    print("No changes needed")
EOF
            
            # Make it executable
            chmod +x add_attribution.py
            
            # Run it
            python add_attribution.py
          else
            echo "Citation source attribution already present"
          fi
          
      - name: Generate citation source visualizations
        run: python scripts/citation_source_heatmap.py
      
      - name: Check if visualizations were created
        run: |
          if [ ! -f citation_source_heatmap.png ] || [ ! -f citation_source_distribution.png ]; then
            echo "Visualization files were not generated properly"
            exit 1
          fi
      
      - name: Commit and push visualizations
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add citation_source_heatmap.png citation_source_distribution.png
          git commit -m "Update citation source visualizations [skip ci]" || exit 0
          git push