name: Citation Data Validation

on:
  # Run after dashboard update workflow completes
  workflow_run:
    workflows:
      - "Dashboard Data Update"
    types:
      - completed
    branches:
      - main
  
  # Run weekly
  schedule:
    # Run every Sunday at 12:00 UTC (after basic repository updates)
    - cron: "0 12 * * 0"
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      skip_doi_check:
        description: 'Skip DOI online validation (faster)'
        type: boolean
        default: false
      auto_fix:
        description: 'Automatically fix DOI format issues'
        type: boolean
        default: true

# Permissions needed for committing changes
permissions:
  contents: write

jobs:
  validate-citations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run citation validation (DOI fixing disabled)
        run: |
          # Build command with appropriate arguments
          CMD="python scripts/validate_citations.py --report"
          
          # Add skip DOI check if specified
          if [[ "${{ github.event.inputs.skip_doi_check }}" == "true" ]]; then
            CMD="$CMD --skip-doi-check"
          fi
          
          # IMPORTANT: DOI fixing has been consolidated to the fix-dois.yml workflow
          # We no longer use the --auto-fix flag here to avoid duplicate fixes
          
          # Run the command
          echo "Running: $CMD"
          $CMD
      
      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: citation-validation-report
          path: |
            reports/citation_validation.json
            reports/citation_validation_report.md
      
      - name: Check for critical issues
        id: check_issues
        run: |
          # Check if the file exists and is valid JSON
          if [ ! -f reports/citation_validation.json ]; then
            echo "Citation validation report file not found"
            echo "issues_count=0" >> $GITHUB_OUTPUT
            echo "inconsistent_dois=0" >> $GITHUB_OUTPUT
            echo "fixed_dois=0" >> $GITHUB_OUTPUT
            echo "CRITICAL_ISSUES=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check for valid JSON
          if ! jq empty reports/citation_validation.json 2>/dev/null; then
            echo "Invalid JSON in citation validation report"
            echo "issues_count=0" >> $GITHUB_OUTPUT
            echo "inconsistent_dois=0" >> $GITHUB_OUTPUT
            echo "fixed_dois=0" >> $GITHUB_OUTPUT
            echo "CRITICAL_ISSUES=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Process the file when it exists and is valid
          ISSUES_COUNT=$(jq '.all_issues | length // 0' reports/citation_validation.json)
          TOOLS_WITH_DOI=$(jq '.tools_with_doi // 0' reports/citation_validation.json)
          CONSISTENT_DOIS=$(jq '.consistent_dois // 0' reports/citation_validation.json)
          FIXED_DOIS=$(jq '.total_dois_fixed // 0' reports/citation_validation.json)
          INCONSISTENT_DOIS=$(jq "($TOOLS_WITH_DOI - $CONSISTENT_DOIS)" 2>/dev/null || echo 0)
          
          # Handle potential arithmetic errors
          if [[ ! "$INCONSISTENT_DOIS" =~ ^[0-9]+$ ]]; then
            INCONSISTENT_DOIS=0
          fi
          
          echo "Total issues found: $ISSUES_COUNT"
          echo "Inconsistent DOIs: $INCONSISTENT_DOIS"
          echo "DOIs auto-fixed: $FIXED_DOIS"
          
          # Set outputs for next steps
          echo "issues_count=$ISSUES_COUNT" >> $GITHUB_OUTPUT
          echo "inconsistent_dois=$INCONSISTENT_DOIS" >> $GITHUB_OUTPUT
          echo "fixed_dois=$FIXED_DOIS" >> $GITHUB_OUTPUT
          
          # Check if there are critical issues that need notification
          if [[ $INCONSISTENT_DOIS -gt 5 ]]; then
            echo "CRITICAL_ISSUES=true" >> $GITHUB_OUTPUT
          else
            echo "CRITICAL_ISSUES=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create GitHub issue for critical problems
        if: steps.check_issues.outputs.CRITICAL_ISSUES == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const reportContent = fs.readFileSync('reports/citation_validation_report.md', 'utf8');
            const fixedDois = ${{ steps.check_issues.outputs.fixed_dois }};
            
            let title = 'Citation Data Validation Critical Issues';
            let bodyIntro = '## Citation Validation Report has identified critical issues';
            
            if (fixedDois > 0) {
              title = `Citation Data Validation: ${fixedDois} DOIs fixed, but critical issues remain`;
              bodyIntro = `## Citation Validation Report\n\n**${fixedDois} DOI format issues were automatically fixed**, but there are still critical consistency issues that need manual review.`;
            }
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: `${bodyIntro}\n\n${reportContent.substring(0, 3000)}...\n\nSee the full report in the workflow artifacts.`,
              labels: ['citation-data', 'data-quality']
            });
      
      - name: Update metrics and commit changes
        run: |
          # Create a directory for citation validation metrics
          mkdir -p reports/citations
          
          # Check if the validation file exists and is valid JSON
          if [ -f reports/citation_validation.json ] && jq empty reports/citation_validation.json 2>/dev/null; then
            # Extract key metrics with safe defaults for missing values
            jq '{
              timestamp: (.timestamp // "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"),
              total_tools: (.total_tools // 0),
              tools_with_doi: (.tools_with_doi // 0),
              doi_percentage: (.doi_percentage // 0),
              valid_doi_percentage: (.valid_doi_percentage // 0),
              consistent_doi_percentage: (.consistent_doi_percentage // 0),
              tools_with_pubmed_data: (.tools_with_pubmed_data // 0),
              pubmed_percentage: (.pubmed_percentage // 0),
              tools_with_academic_impact: (.tools_with_academic_impact // 0),
              academic_impact_percentage: (.academic_impact_percentage // 0),
              citation_format_counts: (.citation_format_counts // {"bibtex": 0, "apa": 0, "mla": 0}),
              issues_count: ((.all_issues | length) // 0),
              total_dois_fixed: (.total_dois_fixed // 0)
            }' reports/citation_validation.json > reports/citations/citation_validation_metrics.json
          else
            # Create empty metrics file if validation results don't exist
            echo '{
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
              "total_tools": 0,
              "tools_with_doi": 0,
              "doi_percentage": 0,
              "valid_doi_percentage": 0,
              "consistent_doi_percentage": 0,
              "tools_with_pubmed_data": 0,
              "pubmed_percentage": 0,
              "tools_with_academic_impact": 0,
              "academic_impact_percentage": 0,
              "citation_format_counts": {"bibtex": 0, "apa": 0, "mla": 0},
              "issues_count": 1,
              "error": "No validation data available"
            }' > reports/citations/citation_validation_metrics.json
          fi
          
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add changes
          git add metadata/**/*.json || true
          git add reports/citations/citation_validation_metrics.json || true
          
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            # Get fixed DOIs count
            FIXED_DOIS=${{ steps.check_issues.outputs.fixed_dois }}
            
            # Create commit message
            if [[ $FIXED_DOIS -gt 0 ]]; then
              COMMIT_MSG="Update citation validation metrics and fix $FIXED_DOIS DOI format issues"
            else
              COMMIT_MSG="Update citation validation metrics"
            fi
            
            # Commit and push
            git commit -m "$COMMIT_MSG [skip ci]"
            git push
            
            echo "Changes committed and pushed to main"
          else
            echo "No changes to commit"
          fi