name: DOI Format Fixing (Authoritative)

on:
  # Run weekly
  schedule:
    # Run every Sunday at 8:00 UTC
    - cron: "0 8 * * 0"
  
  # Allow manual triggering
  workflow_dispatch:

# Permissions needed for committing changes
permissions:
  contents: write

jobs:
  fix-dois:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run DOI auto-fix script (AUTHORITATIVE)
        run: |
          # This is the authoritative script for fixing DOI formatting issues
          # It consolidates functionality previously spread across multiple scripts
          python scripts/auto_fix_dois.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          if ! git diff --quiet; then
            # Add all changes in metadata directory
            git add metadata/
            
            # Commit and push
            git commit -m "Auto-fix DOI format issues [skip ci]"
            git push
          else
            echo "No DOI issues to fix"
          fi