name: Weekly Repository Updates
on:
  schedule:
    # Runs at 00:00 UTC on Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual triggering
jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_UPDATE_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_UPDATE_TOKEN }}
        run: python update_check.py
        run: python create_timeline_image.py
      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Add all potentially changed files, but only if they exist
          git add README.md
          git add repo_data.json starred_repos.md unavailable_repos.md 2>/dev/null || true
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "Weekly repository update [skip ci]"
      - name: Push changes
        run: git push
