name: Update Citation Counts

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Sunday at 3:00 AM UTC
    - cron: '0 3 * * 0'
  
jobs:
  update-citations:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Fix citation counts directly from CrossRef
      run: |
        python scripts/fix_citation_counts.py
        
    - name: Update citation counts from CrossRef
      run: |
        python scripts/update_citation_counts.py
        
    - name: Update impact data with real citations
      run: |
        python scripts/update_impact_from_citations.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add impact_data.json metadata/pubmed_citations/*.json
        git diff --staged --quiet || git commit -m "Update citation counts from CrossRef [skip ci]"
        git push